### ISSUE TITLE
Error: "pydrive.files.ApiRequestError: Cannot download file"

### ISSUE THREAD

**Issue by Ivan-Fan** [royorel/FFHQ-Aging-Dataset#15]
Hi! Really thanks for your great work! This is truly splendid!
I tried to download this dataset using "Download with PyDrive" method, but met some errors here:
```
Authentication successful.
authorized access to google drive API!
Parsing JSON metadata...
Downloading 70001 files...
/ done processing 7/70001 files
Traceback (most recent call last):
  File "D:\Pikachu\Data\FFHQ-Aging-Dataset-master\download_ffhq_aging.py", line 385, in <module>
    run_cmdline(sys.argv)
  File "D:\Pikachu\Data\FFHQ-Aging-Dataset-master\download_ffhq_aging.py", line 380, in run_cmdline
    run(**vars(args))
  File "D:\Pikachu\Data\FFHQ-Aging-Dataset-master\download_ffhq_aging.py", line 358, in run
    download_files(specs, dst_dir, output_size, check_invalid_images, drive=drive, **download_kwargs)
  File "D:\Pikachu\Data\FFHQ-Aging-Dataset-master\download_ffhq_aging.py", line 219, in download_files
    raise exc_info[1].with_traceback(exc_info[2])
  File "D:\Pikachu\Data\FFHQ-Aging-Dataset-master\download_ffhq_aging.py", line 229, in _download_thread
    pydrive_utils.pydrive_download(drive, spec['file_url'], spec['file_path'])
  File "D:\Pikachu\Data\FFHQ-Aging-Dataset-master\pydrive_utils.py", line 40, in pydrive_download
    pydrive_file.GetContentFile(save_path)
  File "C:\Users\Ivan\anaconda3\envs\ffhq\lib\site-packages\pydrive\files.py", line 210, in GetContentFile
    self.FetchContent(mimetype, remove_bom)
  File "C:\Users\Ivan\anaconda3\envs\ffhq\lib\site-packages\pydrive\files.py", line 43, in _decorated
    return decoratee(self, *args, **kwargs)
  File "C:\Users\Ivan\anaconda3\envs\ffhq\lib\site-packages\pydrive\files.py", line 255, in FetchContent
    self.content = io.BytesIO(self._DownloadFromUrl(download_url))
  File "C:\Users\Ivan\anaconda3\envs\ffhq\lib\site-packages\pydrive\auth.py", line 75, in _decorated
    return decoratee(self, *args, **kwargs)
  File "C:\Users\Ivan\anaconda3\envs\ffhq\lib\site-packages\pydrive\files.py", line 505, in _DownloadFromUrl
    raise ApiRequestError('Cannot download file: %s' % resp)
pydrive.files.ApiRequestError: Cannot download file: {'x-guploader-uploadid': 'ADPycds_6rWHi9U3uVhtq9RIMTkqBXLfBlV5ljAR77vIQIzZCSbT2N9ArGCf6ZBGeYeuHbPqWiqg1REEGhvFv80vTJs', 'vary': 'Origin, X-Origin', 'content-type': 'application/json; charset=UTF-8', 'date': 'Wed, 02 Mar 2022 04:04:14 GMT', 'expires': 'Wed, 02 Mar 2022 04:04:14 GMT', 'cache-control': 'private, max-age=0', 'content-length': '320', 'server': 'UploadServer', 'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"', 'status': '403'}
```
I could see that some images have been downloaded successfully, but then this error appears. Could you give some suggestions? Thanks!

**Comment by royorel** [comment]
Hi @Ivan-Fan,

I'm not quite sure what's going on to be honest. It looks like the error is somewhere in the Google Drive API.
The most likely scenario is that the file reached its daily quota limit or that it's been removed (less likely).

One thing you can try to do verify that is to try to download the file manually from google drive. If it succeeds then pydrive should be able to download the file too. If the file reached it quota limit, you will see a "quota exceeded" message.

I hope this helps.

**Comment by Ivan-Fan** [comment]
Thanks! @royorel 
It is strange that things just go smoothly today, even though I did not change anything :) 
Actually, I did not see a "quota exceeded" yesterday. Maybe this problem is because it is my first time using pydrive via my account and it takes time for the initialization?

**Comment by royorel** [comment]
@Ivan-Fan, 

It could've also been a connectivity issue, that can explain why it works today even though it didn't yesterday.

**Comment by Ivan-Fan** [comment]
@royorel That could be the reason! Thanks!
